backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'settings'
    label: 'Settings'
    files:
      - file: 'src/settings/SEO.md'
        label: 'SEO'
        name: 'seo'
        fields:
          - label: 'Meta description'
            name: 'metaDescription'
            widget: 'string'

          - label: 'Meta image'
            name: 'metaImage'
            widget: 'image'

      - file: 'src/settings/header.md'
        label: 'Header'
        name: 'header'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }

      - file: 'src/settings/footer.md'
        label: 'Footer'
        name: 'footer'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - { label: 'Headline Content', name: 'body', widget: 'markdown' }
          - label: 'Portfolio Highlight'
            name: 'portfolioHighlight'
            widget: 'list'
            fields:
              - label: 'Portfolio Name'
                name: 'portfolioName'
                widget: 'relation'
                collection: 'portfolio'
                searchFields: ['title', 'subtitle']
                valueField: 'title'

      - file: 'src/pages/about.md'
        label: 'About Page'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - file: 'src/pages/the-real-deal.md'
        label: 'The Real Deal Page'
        name: 'the-real-deal'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'the-real-deal-page' }
          - { label: 'Headline Content', name: 'body', widget: 'markdown' }

  - name: 'the-real-deal'
    label: 'The Real Deal'
    folder: 'src/content/the-real-deal/'
    create: true
    slug: '{{subtitle}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'the-real-deal-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'src/content/portfolio/'
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      # - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', timeFormat: false, dateFormat: 'YYYY-MM' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
